package iptables

import (
	"fmt"
	"strings"
)

// ToSaveLine converts a Rule back to an iptables-save compatible line.
// e.g. -A INPUT -p tcp --dport 22 -j ACCEPT
func (r *Rule) ToSaveLine(chain string) string {
	var parts []string
	parts = append(parts, "-A", chain)

	if r.InIface != "" {
		parts = append(parts, "-i", r.InIface)
	}
	if r.OutIface != "" {
		parts = append(parts, "-o", r.OutIface)
	}
	if r.Source != "" && r.Source != "0.0.0.0/0" {
		parts = append(parts, "-s", r.Source)
	}
	if r.Dest != "" && r.Dest != "0.0.0.0/0" {
		parts = append(parts, "-d", r.Dest)
	}
	if r.Proto != "" && r.Proto != "all" {
		parts = append(parts, "-p", r.Proto)
	}

	// Modules and their options — order matters for readability
	if state, ok := r.Options["state"]; ok {
		parts = append(parts, "-m", "state", "--state", state)
	}
	if dport, ok := r.Options["dport"]; ok {
		parts = append(parts, "--dport", dport)
	}
	if sport, ok := r.Options["sport"]; ok {
		parts = append(parts, "--sport", sport)
	}
	if dports, ok := r.Options["dports"]; ok {
		parts = append(parts, "-m", "multiport", "--dports", dports)
	}
	if sports, ok := r.Options["sports"]; ok {
		parts = append(parts, "-m", "multiport", "--sports", sports)
	}
	if limit, ok := r.Options["limit"]; ok {
		parts = append(parts, "-m", "limit", "--limit", limit)
		if burst, ok := r.Options["limit-burst"]; ok {
			parts = append(parts, "--limit-burst", burst)
		}
	}
	if icmpType, ok := r.Options["icmp-type"]; ok {
		parts = append(parts, "--icmp-type", icmpType)
	}
	if mac, ok := r.Options["mac-src"]; ok {
		parts = append(parts, "-m", "mac", "--mac-source", mac)
	}
	if comment, ok := r.Options["comment"]; ok {
		parts = append(parts, "-m", "comment", "--comment", `"`+comment+`"`)
	}

	// Target
	parts = append(parts, "-j", r.Target)

	// Target-specific options (after -j)
	if toDst, ok := r.Options["to-dst"]; ok {
		parts = append(parts, "--to-destination", toDst)
	}
	if toSrc, ok := r.Options["to-src"]; ok {
		parts = append(parts, "--to-source", toSrc)
	}
	if toPorts, ok := r.Options["to-ports"]; ok {
		parts = append(parts, "--to-ports", toPorts)
	}
	if logPrefix, ok := r.Options["log-prefix"]; ok {
		parts = append(parts, "--log-prefix", `"`+logPrefix+`"`)
	}
	if logLevel, ok := r.Options["log-level"]; ok {
		parts = append(parts, "--log-level", logLevel)
	}
	if rejectWith, ok := r.Options["reject-with"]; ok {
		parts = append(parts, "--reject-with", rejectWith)
	}

	return strings.Join(parts, " ")
}

// StateToSave serializes the full iptables state in iptables-save format,
// identical to the content of /etc/sysconfig/iptables.
func StateToSave(state *State) string {
	var sb strings.Builder
	sb.WriteString("# Generated by tiptables\n")

	for _, table := range AllTables {
		ts, ok := state.Tables[table]
		if !ok {
			continue
		}

		// Always show filter; skip other tables when completely empty
		if table != TableFilter && !tableHasContent(ts) {
			continue
		}

		sb.WriteString(fmt.Sprintf("*%s\n", table))

		// Chain policy headers
		for _, chainName := range getChainOrder(table, ts) {
			chain := ts.Chains[chainName]
			sb.WriteString(fmt.Sprintf(":%s %s [0:0]\n", chain.Name, chain.Policy))
		}

		// Rules
		for _, chainName := range getChainOrder(table, ts) {
			chain := ts.Chains[chainName]
			for _, rule := range chain.Rules {
				sb.WriteString(rule.ToSaveLine(chainName) + "\n")
			}
		}

		sb.WriteString("COMMIT\n")
	}

	return sb.String()
}

func tableHasContent(ts *TableState) bool {
	for _, chain := range ts.Chains {
		if len(chain.Rules) > 0 {
			return true
		}
		if chain.Policy == "DROP" {
			return true
		}
	}
	return false
}
